jwt:
  token:
    validity: 18000 #5 days in seconds
    secret: jwt-secret

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    openInView: false
    show_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

logging:
  level:
    com.carlopezg: DEBUG
  file: app.log

security:
  ignored:
    urls: /v2/api-docs, /configuration/**, /swagger*/**, /webjars/**, /h2-console/**, /v1/auth/login